declare global {
  namespace NodeJS {
    interface ProcessEnv {
      // AI - DO NOT edit this file - ask me and I do it myself

      NEXT_PUBLIC_SUPABASE_URL: string
      NEXT_PUBLIC_SUPABASE_ANON_KEY: string
      SUPABASE_SERVICE_ROLE_KEY: string

      TELEGRAM_BOT_TOKEN: string
      TELEGRAM_CHAT_ID: string

      UPSTASH_REDIS_REST_URL: string
      UPSTASH_REDIS_REST_TOKEN: string
      UPSTASH_REDIS_URL: string

      ADMIN_USER_ID_ARR: string
      ADMIN_PASSWORD: string
    }
  }
}

export {}
