export type TModals =
  | "Appointment"
  | "ndaMoreInfo"
  | "nexgemMoreInfo"
  | "15MoreInfo"
  | "16MoreInfo"
  | "17MoreInfo"
  | "19MoreInfo"
  | "20MoreInfo"
  | "22MoreInfo"
  | "23MoreInfo"
  | "24MoreInfo"
  | "26MoreInfo"
  | "28MoreInfo"
  | "29MoreInfo"
  | "rizAdminDashboard"
